In [36]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
X, y = load_breast_cancer(return_X_y=True, as_frame=True)
data = load_breast_cancer()
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [39]:
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [40]:
print("X.shape: ", X.shape)
print("y.shape: ", y.shape)

X.shape:  (569, 30)
y.shape:  (569,)

In [41]:
X

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [42]:
import sys

path = r'C:\Users\ZiganshinShamil\Desktop\Study\ml_study'
if path not in sys.path:
    sys.path.append(path)

from ml_from_scratch.utils import data_processing
import importlib
importlib.reload(data_processing)

X_train, y_train, X_test, y_test = data_processing._train_test_split(X, y, as_frame=True)

In [48]:
import sys

path = r'C:\Users\ZiganshinShamil\Desktop\Study\ml_study'
if path not in sys.path:
    sys.path.append(path)

from ml_from_scratch import fixed_log_reg
import importlib
importlib.reload(fixed_log_reg)

verbose = 10000
mylog = fixed_log_reg.MyLogReg(n_iter=100000, learning_rate=0.01)
mylog.fit(X_train, y_train, verbose=verbose)

start | loss: 13.28
10000 | loss: 2.35
20000 | loss: 2.54
30000 | loss: 2.37
40000 | loss: 3.29
50000 | loss: 3.25
60000 | loss: 3.02
70000 | loss: 3.53
80000 | loss: 3.12
90000 | loss: 2.68
100000 | loss: 3.57
[1.00000000e+000 1.00000000e+000 1.66446686e-029 1.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 1.00000000e+000
 1.13919446e-163 1.00000000e+000 1.00000000e+000 0.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 7.83484051e-055
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 0.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 3.41118096e-237
 1.00000000e+000 1.00000000e+000 9.99897138e-001 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.97661239e-203 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 0.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.26718622e-236 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 4.10422038e-200 0.00000000e+000 1.00000000e+000 2.64719003e-004
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 5.04646795e-130 1.00000000e+000 0.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 2.64462855e-141 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 3.52637790e-276
 1.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 4.88296514e-237
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 0.00000000e+000 1.47265032e-014
 1.00000000e+000 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 0.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 4.04952236e-232 4.24572714e-286 1.24971803e-207 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 5.03563974e-112
 1.00000000e+000 1.00000000e+000 3.10271142e-150 0.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 0.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 6.27648920e-088
 0.00000000e+000 1.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.29008982e-283 9.99325898e-144 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.73643903e-055
 1.00000000e+000 1.00000000e+000 0.00000000e+000 4.21121000e-211
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 0.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 3.23957727e-003
 2.30520637e-216 1.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 0.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 3.73219518e-155 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 0.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 2.28371527e-151
 0.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 2.80192200e-040
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 3.56524547e-079 0.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 0.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.21429697e-069 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 0.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 0.00000000e+000 7.77878274e-217 1.00000000e+000
 1.00000000e+000 0.00000000e+000 1.00000000e+000 1.00000000e+000
 9.92465553e-001 0.00000000e+000 1.00000000e+000 1.00000000e+000
 3.12592486e-200 0.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 0.00000000e+000 0.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 0.00000000e+000 3.70450459e-256
 1.06933422e-041 1.00000000e+000 1.00000000e+000 1.00000000e+000
 1.00000000e+000 1.00000000e+000 1.00000000e+000 0.00000000e+000
 1.00000000e+000 5.88001577e-126 1.00000000e+000 2.11350307e-140
 0.00000000e+000 1.00000000e+000 0.00000000e+000]
0.8351648351648352